# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/scudco/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install

autoload -U colors && colors
# get the name of the branch we are on
git_prompt_info() {
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return
      echo "(${ref#refs/heads/})"
}
setopt prompt_subst
PROMPT='
%{$reset_color%}%{$fg_bold[magenta]%}%~ %{$fg_bold[yellow]%}$(git_prompt_info)%{$reset_color%} %E
%{$fg_bold[yellow]%}↳  '
RPROMPT="%{$fg_bold[yellow]%}◴ %t%{$reset_color%}"
export VISUAL=/usr/bin/vim

function title {
  if [[ $TERM == "screen" ]]; then
    # Use these two for GNU Screen:
    print -nR $'\033k'$1$'\033'\\
    print -nR $'\033]0;'$2$'\a'
  elif [[ $TERM == "xterm" || $TERM == "rxvt" ]]; then
    # Use this one instead for XTerms:
    print -nR $'\033]0;'$*$'\a'
  fi
}

function precmd {
  title zsh "$PWD"
}

function preexec {
  emulate -L zsh
  local -a cmd; cmd=(${(z)1})
  title $cmd[1]:t "$cmd[2,-1]"
}

export PATH=~/bin:~/.seeds/bin:/usr/local/bin:/usr/local/sbin:$PATH

# ALIASES
alias ls='ls -G'

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'
alias l='lla -CF'

alias g='git'
alias tu='tar zxvf'
alias less='less -r'
alias screen='screen -T xterm-256color'
alias ss='screen -S'
alias screens='ss screens -c ~/.screens'
alias visor='ss visor -c ~/.visor_screens'
alias inbox='cd ~/inbox'
alias node-repl="rlwrap node-repl"
define() { wn $* -over; }
alias gvim='mvim'

#ruby
alias r='rails'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

source ~/.git-flow-completion.zsh

# Thank you http://twistedmind.com/bundle-exec-bash-shortcut
bundle_commands=( spec rspec cucumber cap watchr rails rackup autotest heroku )

function run_bundler_cmd () {
    if [ -e ./Gemfile ]; then
        echo "bundle exec $@"
        bundle exec $@
    else
        echo "$@"
        $@
    fi
}

for cmd in $bundle_commands
do
    alias $cmd="run_bundler_cmd $cmd"
done
# End thank you

# Ruby Enterprise Edition Settings
export RUBY_HEAP_MIN_SLOTS=3000000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=1000000000
export RUBY_HEAP_FREE_MIN=500000
