#!/usr/bin/env ruby
require 'optparse'
def self.show_help(opts=nil)
  puts opts || get_opts
  exit
end

options = {}
opt_p = OptionParser.new do |opts|
  opts.banner = "Usage: script/run [options]"
  opts.separator "Options:"
  opts.on("-c", "--command command")         { |command|     options[:command]     = command }
  opts.on("-f", "--file [file]")               { |file|        ENV['TM_FILEPATH']    = file }
  opts.on("-l", "--line_number [line_number]") { |line_number| ENV['TM_LINE_NUMBER'] = line_number }
  opts.on_tail("-h", "--help", "Show this message") { @show_help = true }
end
opt_p.parse!
show_help(opt_p) if @show_help

require File.dirname(__FILE__) + "/../lib/ruby_amp.rb"

RubyAMP::Commands.send(options[:command])
